version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root
#version: 0.0
#os: linux
#files:
#  - source: /
#    destination: /home/ec2-usergit p
#hooks:
#  AfterInstall:
#    - location: scripts/install_app_dependencies
#      timeout: 100
#  ApplicationStart:
#    - location: scripts/start_server
#      timeout: 100